name: CI

# ✅ Give write permission so workflow can push to gh-pages
permissions:
  contents: write

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MAVEN_OPTS: -Xmx2g

    steps:
      # Step 1: Checkout
      - name: Checkout
        uses: actions/checkout@v4

      # Step 2: Set up Java
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      # Step 3: Build and Run Tests
      - name: Run Tests (headless)
        run: mvn test -B -Dheadless=true

      # Step 4: Generate Cucumber Report
      - name: Generate Cucumber HTML Report
        run: mvn verify -DskipTests

      # Step 5: Upload Cucumber Reports as Artifact (optional but useful)
      - name: Upload cucumber reports
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-reports
          path: target/cucumber-reports

      # Step 6: 🚀 Deploy Report to GitHub Pages
      - name: Deploy Cucumber HTML Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ACTIONS_DEPLOY_TOKEN }}  # ✅ Your PAT secret
          publish_dir: ./target/cucumber-reports
