name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MAVEN_OPTS: -Xmx2g
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: 'maven'

      - name: Display Chrome version
        run: google-chrome --version || true

      - name: Run tests (headless)
        run: mvn test -B -Dheadless=true

      - name: Generate Masterthought report
        run: |
          mvn -q -DskipTests=true exec:java -Dexec.mainClass="com.testautomation.utils.ReportGenerator" || true

      - name: Upload cucumber reports
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-reports
          path: target/cucumber-reports

      - name: Upload surefire reports
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: target/surefire-reports

      - name: Upload masterthought html (if exists)
        uses: actions/upload-artifact@v4
        with:
          name: masterthought-report
          path: target/cucumber-reports
